name: WASM Build

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Import emscripten
      uses: mymindstorm/setup-emsdk@v9
      
    - name: Configure CMake and build
      run:  |
        mkdir build
        cd build

        emcmake cmake \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DZ3_BUILD_LIBZ3_SHARED=OFF \
          -DZ3_ENABLE_EXAMPLE_TARGETS=OFF \
          -DZ3_BUILD_TEST_EXECUTABLES=OFF \
          -DZ3_BUILD_EXECUTABLE=OFF \
          -DZ3_SINGLE_THREADED=ON \
          -DCMAKE_CXX_FLAGS="-s DISABLE_EXCEPTION_CATCHING=0" \
          ..; 
        make
        tar -cvf z3-build-wasm.tar *.a
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: z3-build-wasm
        path: build/z3-build-wasm.tar
